# Generated by Django 2.2 on 2020-09-13 14:59

from django.db import migrations, models
import properties.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=150)),
                ('property_type', models.CharField(choices=[('Bungalow', 'Bungalow'), ('Condo', 'Condo'), ('Duplex', 'Duplex'), ('Flat', 'Flat'), ('Self_Contain', 'Self Contain'), ('land', 'Land'), ('Storey_Building', 'Storey Building')], default='Self_Contain', max_length=120)),
                ('sqft', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('bedrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('image1', models.ImageField(blank=True, null=True, upload_to=properties.models.upload_image_path)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=properties.models.upload_image_path)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=properties.models.upload_image_path)),
                ('image4', models.ImageField(blank=True, null=True, upload_to=properties.models.upload_image_path)),
                ('image5', models.ImageField(blank=True, null=True, upload_to=properties.models.upload_image_path)),
                ('image6', models.ImageField(blank=True, null=True, upload_to=properties.models.upload_image_path)),
                ('featured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('availability', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
    ]
