# Generated by Django 2.2 on 2020-09-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20200913_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
