# Generated by Django 2.2 on 2020-09-14 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_auto_20200914_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
    ]
