# Generated by Django 2.2.12 on 2020-09-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20200905_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
