# Generated by Django 2.2.12 on 2020-09-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_properties_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='property_size',
            field=models.IntegerField(default=0),
        ),
    ]
