# Generated by Django 2.2.12 on 2020-09-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_properties_property_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='bungalow',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='properties',
            name='availability',
            field=models.CharField(choices=[('For Sale', 'For_Sale'), ('For Rent', 'For_Rent')], default='For_Sale', max_length=120),
        ),
    ]
