# Generated by Django 2.2.12 on 2020-09-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_auto_20200906_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='_storey_building',
            field=models.BooleanField(default=False),
        ),
    ]
