# Generated by Django 2.2.12 on 2020-09-06 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_properties__storey_building'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='_storey_building',
        ),
        migrations.RemoveField(
            model_name='properties',
            name='bungalow',
        ),
    ]
