<<<<<<< Updated upstream:properties/migrations/0001_initial.py
# Generated by Django 2.2.12 on 2020-09-05 21:11
=======
# Generated by Django 2.2.12 on 2020-09-15 10:38
>>>>>>> Stashed changes:Property/migrations/0001_initial.py

from django.db import migrations, models
import Property.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=150)),
<<<<<<< Updated upstream:properties/migrations/0001_initial.py
                ('property_type', models.CharField(choices=[('Bungalow', 'Bungalow'), ('Condo', 'Condo'), ('Duplex', 'Duplex'), ('Flat', 'Flat'), ('Self Contain', 'Self Contain'), ('Storey Building', 'Storey Building'), ('2 Storey Building', '2 Storey Building')], default='flat', max_length=120)),
                ('price', models.CharField(max_length=18)),
                ('bedrooms', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
                ('bathrooms', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1)),
                ('image1', models.ImageField(blank=True, null=True, upload_to=properties.models.upload_image_path)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=properties.models.upload_image_path)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=properties.models.upload_image_path)),
                ('image4', models.ImageField(blank=True, null=True, upload_to=properties.models.upload_image_path)),
                ('image5', models.ImageField(blank=True, null=True, upload_to=properties.models.upload_image_path)),
                ('image6', models.ImageField(blank=True, null=True, upload_to=properties.models.upload_image_path)),
=======
                ('property_type', models.CharField(choices=[('Bungalow', 'Bungalow'), ('Condo', 'Condo'), ('Duplex', 'Duplex'), ('Flat', 'Flat'), ('Self_Contain', 'Self Contain'), ('land', 'Land'), ('Storey_Building', 'Storey Building')], default='Self_Contain', max_length=120)),
                ('sqft', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=0, max_digits=20)),
                ('bedrooms', models.DecimalField(decimal_places=0, max_digits=2)),
                ('bathrooms', models.DecimalField(decimal_places=0, max_digits=2)),
                ('image1', models.ImageField(blank=True, null=True, upload_to=Property.models.upload_image_path)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=Property.models.upload_image_path)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=Property.models.upload_image_path)),
                ('image4', models.ImageField(blank=True, null=True, upload_to=Property.models.upload_image_path)),
                ('image5', models.ImageField(blank=True, null=True, upload_to=Property.models.upload_image_path)),
                ('image6', models.ImageField(blank=True, null=True, upload_to=Property.models.upload_image_path)),
>>>>>>> Stashed changes:Property/migrations/0001_initial.py
                ('featured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('availability', models.CharField(choices=[('For Sale', 'For_Sale'), ('For Rent', 'For_Rent')], default='for_sale', max_length=120)),
                ('not_available', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
