# Generated by Django 2.2.12 on 2020-09-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
        ('properties', '0002_properties_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='agent',
        ),
        migrations.AddField(
            model_name='properties',
            name='agent',
            field=models.ManyToManyField(blank=True, null=True, to='agency.Agency'),
        ),
    ]
