# Generated by Django 2.2.12 on 2020-09-05 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
        ('properties', '0003_auto_20200905_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='agent',
        ),
        migrations.AddField(
            model_name='properties',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agency.Agency'),
        ),
    ]
